### ISSUE TITLE
RangeError in Transaction.fromBuffer

### ISSUE THREAD

**Issue by xloem** [kevinejohn/bsv-minimal#1]
I'm bumping into this issue at the moment:
```
> bsvmin.Transaction.fromBuffer(tx)
Thrown:
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 780. Received 790
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readUInt32LE (internal/buffer.js:181:5)
    at BufferReader.readUInt32LE (/shared/src/bsv-p2p/node_modules/bsv-minimal/src/utils/reader.js:73:24)
    at Function.fromBufferReader (/shared/src/bsv-p2p/node_modules/bsv-minimal/src/transaction.js:23:21)
    at Function.fromBuffer (/shared/src/bsv-p2p/node_modules/bsv-minimal/src/transaction.js:10:15)
```

**Comment by kevinejohn** [comment]
Did you ever get this working? Can you post the transaction hex that throws this error?

**Comment by xloem** [comment]
Looking at my code it looks like I ended up using a different library ...  I'm possibly recalling it was a transaction from the network.  I wrote a test script to try on scads of transactions I have published with the project, and so far they are all parsing without the error.  Do you think it would have been resolved?

**Comment by xloem** [comment]
I found the transaction that caused the error in my terminal logs.  The problem was that I was passing hexadecimal data to the function, instead of binary data.  So, just my error, unless you consider that a bug.  Thanks for checking up on it.

**Comment by xloem** [comment]
Some context:  I was working with this to try to add p2p support to https://github.com/monkeylord/bsvup, a task I haven't had the capacity to complete.  My work is at that repo as a pull request.

I've also poked at https://github.com/libbtc/libbtc, a c library, which seems to work well enough for bsv.  It has an active fork but somebody needs to stir the community to get a new or old maintainer to address the open pull requests.
